"""empty message

Revision ID: edf9739cd316
Revises: 
Create Date: 2023-08-26 21:38:00.665784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf9739cd316'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sprite', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('element', sa.String(), nullable=True),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('base_defense', sa.Integer(), nullable=False),
    sa.Column('base_attack', sa.Integer(), nullable=False),
    sa.Column('abilities', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('partied_pokemon',
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('partied_pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partied_pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], )
    )
    op.create_table('stored_pokemon',
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('stored_pokemon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stored_pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_pokemon')
    op.drop_table('partied_pokemon')
    op.drop_table('user')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
